import { MedicalSupplyItem } from '../types';

export const FULL_SUPPLIES_CATALOG: MedicalSupplyItem[] = [
  { id: 'loc-1', name: 'Nitrile Examination Gloves (100pcs)', description: 'Powder-free medical grade nitrile gloves', price_jmd: 2100, category: 'PPE', stock: 100, image_url: '/src/assets/images/wound_dressing.jpg', is_active: true },
  { id: 'loc-2', name: 'Adult Diapers Large (20pcs)', description: 'Super absorbent adult diapers with tabs', price_jmd: 3500, category: 'Elderly Care', stock: 50, image_url: '/src/assets/images/senior_respite.jpg', is_active: true },
  { id: 'loc-3', name: 'Bed Underpads / Chux (30pcs)', description: 'Waterproof bed pads 60x90cm', price_jmd: 2800, category: 'Elderly Care', stock: 80, image_url: '/src/assets/images/mobility_hydration.jpg', is_active: true },
  { id: 'loc-4', name: 'Unscented Adult Wet Wipes (80pcs)', description: 'Gentle alcohol-free cleansing wipes', price_jmd: 1200, category: 'Elderly Care', stock: 120, image_url: '/src/assets/images/palliative_comfort.jpg', is_active: true },
  { id: 'loc-5', name: 'Disposable Face Masks (50pcs)', description: '3-ply surgical masks', price_jmd: 1500, category: 'PPE', stock: 200, image_url: '/src/assets/images/medication_management.jpg', is_active: true },
  { id: 'loc-6', name: 'Sterile Gauze Wound Dressing 10-Pack', description: 'Sterile gauze pads for wound care', price_jmd: 1200, category: 'Wound Care', stock: 90, image_url: '/src/assets/images/wound_dressing.jpg', is_active: true },
  { id: 'loc-7', name: 'Antiseptic Wash Solution', description: 'Chlorhexidine antiseptic 500ml', price_jmd: 1800, category: 'Wound Care', stock: 60, image_url: '/src/assets/images/iv_therapy.jpg', is_active: true },
  { id: 'loc-8', name: 'Medical Tape (6 rolls)', description: 'Hypoallergenic surgical tape', price_jmd: 1200, category: 'Wound Care', stock: 100, image_url: '/src/assets/images/elderly_vitals.jpg', is_active: true },
  { id: 'loc-9', name: 'Digital BP Monitor', description: 'Automatic upper arm blood pressure monitor', price_jmd: 6500, category: 'Diagnostic', stock: 25, image_url: '/src/assets/images/vitals_monitoring.jpg', is_active: true },
  { id: 'loc-10', name: 'Pulse Oximeter Fingertip', description: 'LED pulse oximeter for oxygen saturation', price_jmd: 4500, category: 'Diagnostic', stock: 30, image_url: '/src/assets/images/vitals_monitoring.jpg', is_active: true },
  { id: 'loc-11', name: 'First Aid & Emergency Kit', description: 'Complete 100-piece first aid kit', price_jmd: 5000, category: 'Emergency', stock: 40, image_url: '/src/assets/images/senior_respite.jpg', is_active: true },
  { id: 'loc-12', name: 'Hand Sanitizer 500ml', description: '70% alcohol hand sanitizer gel', price_jmd: 1200, category: 'PPE', stock: 150, image_url: '/src/assets/images/palliative.jpg', is_active: true },
  { id: 'loc-13', name: 'Digital Thermometer', description: 'Fast read digital thermometer', price_jmd: 1800, category: 'Diagnostic', stock: 70, image_url: '/src/assets/images/elderly_vitals.jpg', is_active: true },
  { id: 'loc-14', name: 'Glucometer + 50 Strips', description: 'Blood glucose monitoring system', price_jmd: 5800, category: 'Diagnostic', stock: 20, image_url: '/src/assets/images/vitals_monitoring.jpg', is_active: true },
  { id: 'loc-15', name: 'Weekly Pill Organizer', description: '7-day AM/PM pill case', price_jmd: 900, category: 'Medication', stock: 100, image_url: '/src/assets/images/medication_management.jpg', is_active: true },
  { id: 'loc-16', name: 'Isolation Gowns (10pcs)', description: 'Disposable fluid resistant gowns', price_jmd: 3800, category: 'PPE', stock: 60, image_url: '/src/assets/images/palliative.jpg', is_active: true },
  { id: 'loc-17', name: 'Bedside Commode Chair', description: 'Steel commode chair with bucket', price_jmd: 18500, category: 'Mobility', stock: 10, image_url: '/src/assets/images/mobility_hydration.jpg', is_active: true },
  { id: 'loc-18', name: 'Shower Chair', description: 'Non-slip adjustable shower bench', price_jmd: 12500, category: 'Mobility', stock: 12, image_url: '/src/assets/images/mobility_hydration.jpg', is_active: true },
  { id: 'loc-19', name: 'Walker with Wheels', description: 'Foldable walker with 2 wheels', price_jmd: 16500, category: 'Mobility', stock: 15, image_url: '/src/assets/images/mobility_hydration.jpg', is_active: true },
  { id: 'loc-20', name: 'No-Rinse Cleansing Foam', description: 'Perineal cleansing foam 250ml', price_jmd: 1600, category: 'Elderly Care', stock: 80, image_url: '/src/assets/images/palliative_comfort.jpg', is_active: true },
  { id: 'loc-21', name: 'Barrier Cream Zinc Oxide', description: 'Protects against diaper rash', price_jmd: 1400, category: 'Elderly Care', stock: 70, image_url: '/src/assets/images/palliative_comfort.jpg', is_active: true },
  { id: 'loc-22', name: 'Non-Stick Wound Pads (20pcs)', description: 'Absorbent wound dressings', price_jmd: 1600, category: 'Wound Care', stock: 60, image_url: '/src/assets/images/wound_dressing.jpg', is_active: true },
  { id: 'loc-23', name: 'Alcohol Prep Pads (200pcs)', description: '70% isopropyl alcohol pads', price_jmd: 1100, category: 'Wound Care', stock: 110, image_url: '/src/assets/images/iv_therapy.jpg', is_active: true },
  { id: 'loc-24', name: 'Blood Pressure Cuff Replacement', description: 'Universal BP cuff', price_jmd: 3200, category: 'Diagnostic', stock: 20, image_url: '/src/assets/images/vitals_monitoring.jpg', is_active: true },
  { id: 'loc-25', name: 'Bed Rail Safety Guard', description: 'Adjustable bed safety rail', price_jmd: 14500, category: 'Mobility', stock: 8, image_url: '/src/assets/images/mobility_hydration.jpg', is_active: true },
];
