import React, { useState, useEffect, useRef } from 'react';
import QRCode from 'qrcode';
import { AutoGeneratedQRCode } from '../common/AutoGeneratedQRCode';
import { NurseProfile } from '../../types';
import { 
  createNurseInviteQR, 
  getNurseInviteQRs, 
  markNurseInviteUsed, 
  saveNurseProfile, 
  NurseInviteQR 
} from '../../services/qrFirebaseStore';
import { 
  QrCode, 
  Sparkles, 
  Smartphone, 
  ShieldCheck, 
  CheckCircle2, 
  Copy, 
  Check, 
  Download, 
  Printer, 
  UserPlus, 
  Clock, 
  RefreshCw, 
  ListOrdered,
  AlertTriangle,
  MapPin,
  Stethoscope
} from 'lucide-react';
import confetti from 'canvas-confetti';

interface NurseQRCodeSignUpModalProps {
  isOpen: boolean;
  onClose: () => void;
  onQuickSignUpNurse?: (newNurse: NurseProfile) => void;
}

const JAMAICAN_PARISHES = [
  'Kingston',
  'St. Andrew',
  'St. Catherine',
  'Clarendon',
  'Manchester',
  'St. Elizabeth',
  'Westmoreland',
  'Hanover',
  'St. James',
  'Trelawny',
  'St. Ann',
  'St. Mary',
  'Portland',
  'St. Thomas'
];

const SERVICE_TYPES = [
  'Elderly Care & Vitals',
  'Wound Care & Post-Op Recovery',
  'IV Therapy & Scheduled Injections',
  'Palliative & Respite Comfort Care',
  'Postnatal & Newborn Midwifery',
  'Specialized Chronic Disease Management',
  'Emergency Response & Phlebotomy'
];

export const NurseQRCodeSignUpModal: React.FC<NurseQRCodeSignUpModalProps> = ({
  isOpen,
  onClose,
  onQuickSignUpNurse
}) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  // Invite state
  const [currentInvite, setCurrentInvite] = useState<NurseInviteQR | null>(null);
  const [allInvites, setAllInvites] = useState<NurseInviteQR[]>([]);
  const [timeLeftString, setTimeLeftString] = useState<string>('23:59:59');
  const [copiedLink, setCopiedLink] = useState(false);
  const [activeTab, setActiveTab] = useState<'qr' | 'form' | 'list'>('qr');

  // Onboarding Form fields per prompt:
  // Full Name, TRN, NCJ License #, Phone, Parish, Service Type
  const [fullName, setFullName] = useState('');
  const [trn, setTrn] = useState('');
  const [ncjLicense, setNcjLicense] = useState('');
  const [phone, setPhone] = useState('');
  const [parish, setParish] = useState('Kingston');
  const [serviceType, setServiceType] = useState('Elderly Care & Vitals');
  const [formSuccess, setFormSuccess] = useState(false);

  // 1. Initialize or load dynamic active invite QR on open
  useEffect(() => {
    if (!isOpen) return;

    const existing = getNurseInviteQRs();
    setAllInvites(existing);

    // Find the latest active and non-expired invite
    const now = Date.now();
    const active = existing.find(i => !i.used && i.expiresAt > now);

    if (active) {
      setCurrentInvite(active);
    } else {
      // Auto-generate fresh unique 24-hr invite
      const fresh = createNurseInviteQR();
      setCurrentInvite(fresh);
      setAllInvites(getNurseInviteQRs());
    }
  }, [isOpen]);

  // 2. Render dynamic QR onto Canvas via 'qrcode'
  useEffect(() => {
    if (!isOpen || !currentInvite || !canvasRef.current) return;

    QRCode.toCanvas(
      canvasRef.current,
      currentInvite.url,
      {
        width: 250,
        margin: 2,
        color: {
          dark: '#1E1B4B', // Navy #1E1B4B
          light: '#FFFFFF'
        },
        errorCorrectionLevel: 'H'
      },
      (err) => {
        if (err) console.error('Error generating nurse QR canvas', err);
      }
    );
  }, [isOpen, currentInvite, activeTab]);

  // 3. Dynamic countdown: "Expires in 23:59:59"
  useEffect(() => {
    if (!isOpen || !currentInvite) return;

    const interval = setInterval(() => {
      const now = Date.now();
      const diff = currentInvite.expiresAt - now;

      if (diff <= 0) {
        setTimeLeftString('00:00:00 (EXPIRED)');
      } else {
        const hours = Math.floor(diff / (1000 * 60 * 60));
        const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
        const seconds = Math.floor((diff % (1000 * 60)) / 1000);
        setTimeLeftString(
          `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`
        );
      }
    }, 1000);

    return () => clearInterval(interval);
  }, [isOpen, currentInvite]);

  if (!isOpen) return null;

  // Handler: Generate fresh invite immediately
  const handleGenerateNewInvite = () => {
    const fresh = createNurseInviteQR();
    setCurrentInvite(fresh);
    setAllInvites(getNurseInviteQRs());
  };

  const handleCopyLink = () => {
    if (!currentInvite) return;
    navigator.clipboard?.writeText(currentInvite.url);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2500);
  };

  const handleDownloadQR = () => {
    if (!canvasRef.current) return;
    try {
      const dataUrl = canvasRef.current.toDataURL('image/png');
      const link = document.createElement('a');
      link.href = dataUrl;
      link.download = `wecare-nurse-signup-qr-${currentInvite?.id || 'live'}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (e) {
      console.warn('Download QR failed', e);
    }
  };

  const handleFastFillSample = () => {
    setFullName('Nurse Tiana Blake, RN');
    setTrn('108-492-817');
    setNcjLicense('NCJ-RN-2023-9912');
    setPhone('+1 (876) 555-8392');
    setParish('St. Andrew');
    setServiceType('Wound Care & Post-Op Recovery');
  };

  // Submit Onboarding Form:
  // Saves to /nurses/{uid}, marks invite used in /qr_invites/{qrId}, adds nurse profile
  const handleSubmitForm = (e: React.FormEvent) => {
    e.preventDefault();
    if (!fullName || !trn || !ncjLicense || !phone) return;

    const uid = `nurse-qr-${Date.now()}`;

    // 1. Save to /nurses/{uid} and mark invite used
    saveNurseProfile(uid, {
      fullName,
      trn,
      ncjLicense,
      phone,
      parish,
      serviceType,
      inviteId: currentInvite?.id
    });

    // 2. Build full NurseProfile for in-memory app roster
    const newNurse: NurseProfile = {
      id: uid,
      name: fullName,
      phone,
      email: `${fullName.toLowerCase().replace(/[^a-z]/g, '')}@wecare.jm`,
      photoUrl: 'https://images.unsplash.com/photo-1594824813570-781e600570b5?auto=format&fit=crop&q=80&w=400',
      nursingCouncilLicense: ncjLicense,
      trnNumber: trn,
      licenseVerified: false,
      status: 'pending_approval',
      rating: 5.0,
      reviewCount: 1,
      yearsExperience: 4,
      specialties: [serviceType, 'Vitals Monitoring', 'Emergency Response'],
      zones: [parish, 'New Kingston & Liguanea', 'Portmore'],
      hourlyRateJMD: 7500,
      bio: `NCJ Registered Nurse (${ncjLicense}) registered via WeCare dynamic invite in ${parish}. TRN: ${trn}. Specialty: ${serviceType}.`,
      totalEarningsJMD: 0,
      pendingPayoutJMD: 0,
      completedVisitsCount: 0
    };

    if (onQuickSignUpNurse) {
      onQuickSignUpNurse(newNurse);
    }

    confetti({
      particleCount: 100,
      spread: 70,
      origin: { y: 0.6 },
      colors: ['#1E1B4B', '#F59E0B', '#3B82F6', '#10B981']
    });

    setFormSuccess(true);
    setTimeout(() => {
      setFormSuccess(false);
      onClose();
    }, 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-[#0a0518]/90 backdrop-blur-xl animate-fadeIn overflow-y-auto">
      <div 
        className="w-full max-w-2xl bg-[#0f0a26] border-2 rounded-3xl p-5 sm:p-7 shadow-2xl text-white my-auto relative max-h-[94vh] overflow-y-auto"
        style={{ borderColor: '#1E1B4B' }}
      >
        {/* Header */}
        <div className="flex items-start justify-between pb-4 border-b border-white/10">
          <div>
            <div className="flex items-center gap-2">
              <span 
                className="px-3 py-1 rounded-full text-xs font-black uppercase tracking-wider text-[#1E1B4B] flex items-center gap-1.5 shadow-sm"
                style={{ backgroundColor: '#F59E0B' }}
              >
                <QrCode className="w-3.5 h-3.5 text-[#1E1B4B]" />
                <span>Live Dynamic QR Invite</span>
              </span>
              <span className="text-xs text-slate-400">NCJ Fast-Track Onboarding</span>
            </div>
            <h2 className="text-xl sm:text-2xl font-black text-white mt-1.5 flex items-center gap-2">
              <span>Nurse Sign-Up QR Code</span>
            </h2>
            <p className="text-xs text-slate-300 mt-1">
              Auto-generated scannable QR. Each invite expires after 24 hours. Saved to <span className="font-mono text-amber-300">/qr_invites</span>.
            </p>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-white/10 transition cursor-pointer"
            aria-label="Close"
          >
            ✕
          </button>
        </div>

        {/* Tab Switcher */}
        <div className="flex items-center gap-2 my-4 bg-white/5 p-1 rounded-2xl border border-white/10 text-xs">
          <button
            onClick={() => setActiveTab('qr')}
            className={`flex-1 py-2.5 rounded-xl font-bold transition flex items-center justify-center gap-1.5 cursor-pointer ${
              activeTab === 'qr'
                ? 'bg-[#1E1B4B] text-white border border-[#F59E0B]/50 shadow-md'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            <QrCode className="w-4 h-4 text-amber-400" />
            <span>1. Dynamic Invite QR</span>
          </button>
          <button
            onClick={() => setActiveTab('form')}
            className={`flex-1 py-2.5 rounded-xl font-bold transition flex items-center justify-center gap-1.5 cursor-pointer ${
              activeTab === 'form'
                ? 'bg-[#1E1B4B] text-white border border-[#F59E0B]/50 shadow-md'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            <UserPlus className="w-4 h-4 text-blue-400" />
            <span>2. Nurse Onboarding Form</span>
          </button>
          <button
            onClick={() => {
              setActiveTab('list');
              setAllInvites(getNurseInviteQRs());
            }}
            className={`flex-1 py-2.5 rounded-xl font-bold transition flex items-center justify-center gap-1.5 cursor-pointer ${
              activeTab === 'list'
                ? 'bg-[#1E1B4B] text-white border border-[#F59E0B]/50 shadow-md'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            <ListOrdered className="w-4 h-4 text-emerald-400" />
            <span>3. Manage Invites ({allInvites.length})</span>
          </button>
        </div>

        {/* TAB 1: DYNAMIC QR CODE DISPLAY */}
        {activeTab === 'qr' && (
          <div className="space-y-5">
            {/* Countdown Badge */}
            <div className="flex items-center justify-between p-3 rounded-2xl bg-gradient-to-r from-[#1E1B4B]/80 to-slate-900 border border-[#F59E0B]/40">
              <div className="flex items-center gap-2">
                <Clock className="w-4 h-4 text-[#F59E0B] animate-spin" />
                <span className="text-xs font-bold text-slate-200">
                  Invite ID: <span className="font-mono text-amber-300">{currentInvite?.id || 'LOADING'}</span>
                </span>
              </div>
              <div className="px-3 py-1 rounded-xl bg-black/60 border border-[#F59E0B]/60 text-xs font-mono font-black text-[#F59E0B]">
                Expires in {timeLeftString}
              </div>
            </div>

            {/* Auto-Generated Pure QR Code - NO center logo overlay */}
            <div className="flex flex-col items-center justify-center p-4 rounded-3xl bg-white/[0.03] border border-white/10">
              <AutoGeneratedQRCode
                value={currentInvite?.url}
                qrId={currentInvite?.id}
                countdown={timeLeftString}
                showActions={false}
              />
            </div>

            {/* Action Buttons */}
            <div className="flex flex-wrap items-center justify-between gap-2.5 pt-1">
              <button
                type="button"
                onClick={handleGenerateNewInvite}
                className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-[#1E1B4B] to-blue-900 hover:opacity-90 text-white text-xs font-bold transition flex items-center gap-1.5 border border-[#F59E0B]/50 cursor-pointer shadow-md"
              >
                <RefreshCw className="w-3.5 h-3.5 text-[#F59E0B]" />
                <span>Generate New Nurse Invite QR</span>
              </button>

              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleCopyLink}
                  className="px-3.5 py-2.5 rounded-xl bg-white/10 hover:bg-white/15 text-white text-xs font-bold transition flex items-center gap-1.5 border border-white/10 cursor-pointer"
                >
                  {copiedLink ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-amber-300" />}
                  <span>{copiedLink ? 'Copied!' : 'Copy Link'}</span>
                </button>
                <button
                  type="button"
                  onClick={handleDownloadQR}
                  className="px-3.5 py-2.5 rounded-xl bg-white/10 hover:bg-white/15 text-white text-xs font-bold transition flex items-center gap-1.5 border border-white/10 cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5 text-blue-400" />
                  <span>Download PNG</span>
                </button>
              </div>
            </div>
          </div>
        )}

        {/* TAB 2: NURSE ONBOARDING FORM */}
        {activeTab === 'form' && (
          <form onSubmit={handleSubmitForm} className="space-y-4">
            <div className="p-3.5 rounded-2xl bg-gradient-to-r from-[#1E1B4B]/80 to-blue-950/70 border border-[#F59E0B]/40 flex items-center justify-between">
              <div>
                <span className="text-xs font-bold text-[#F59E0B] block">Nurse Onboarding Profile Creation</span>
                <p className="text-[11px] text-slate-300">When scanned, this form creates the nurse profile in <span className="font-mono text-white">/nurses/[uid]</span>.</p>
              </div>
              <button
                type="button"
                onClick={handleFastFillSample}
                className="px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/15 text-amber-300 text-xs font-bold transition border border-white/10 shrink-0 cursor-pointer"
              >
                Auto-Fill Sample
              </button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
              {/* Full Name */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1">Full Name &amp; Title *</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Nurse Tiana Blake, RN"
                  value={fullName}
                  onChange={(e) => setFullName(e.target.value)}
                  className="w-full bg-black/40 border border-white/15 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-[#F59E0B]"
                />
              </div>

              {/* TRN (Tax Registration Number) */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1">TRN (Tax Registration Number) *</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. 108-492-817"
                  value={trn}
                  onChange={(e) => setTrn(e.target.value)}
                  className="w-full bg-black/40 border border-white/15 rounded-xl px-3.5 py-2.5 text-xs text-white font-mono placeholder-slate-500 focus:outline-none focus:border-[#F59E0B]"
                />
              </div>

              {/* NCJ License # */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1">NCJ License # *</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. NCJ-RN-2023-9912"
                  value={ncjLicense}
                  onChange={(e) => setNcjLicense(e.target.value)}
                  className="w-full bg-black/40 border border-white/15 rounded-xl px-3.5 py-2.5 text-xs text-white font-mono placeholder-slate-500 focus:outline-none focus:border-[#F59E0B]"
                />
              </div>

              {/* Phone */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1">Phone Number *</label>
                <input
                  type="tel"
                  required
                  placeholder="e.g. +1 (876) 555-8392"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  className="w-full bg-black/40 border border-white/15 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-[#F59E0B]"
                />
              </div>

              {/* Parish */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1">Parish *</label>
                <select
                  value={parish}
                  onChange={(e) => setParish(e.target.value)}
                  className="w-full bg-black/40 border border-white/15 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-[#F59E0B]"
                >
                  {JAMAICAN_PARISHES.map((p) => (
                    <option key={p} value={p} className="bg-[#0f0a26] text-white">
                      {p}
                    </option>
                  ))}
                </select>
              </div>

              {/* Service Type */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1">Service Type *</label>
                <select
                  value={serviceType}
                  onChange={(e) => setServiceType(e.target.value)}
                  className="w-full bg-black/40 border border-white/15 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-[#F59E0B]"
                >
                  {SERVICE_TYPES.map((s) => (
                    <option key={s} value={s} className="bg-[#0f0a26] text-white">
                      {s}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div className="p-3 rounded-2xl bg-white/5 border border-white/10 text-xs text-slate-300 flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0" />
              <span>
                Creates nurse record in <span className="font-mono text-emerald-300">/nurses</span> and marks invite as used (<span className="font-mono text-amber-300">used: true</span>).
              </span>
            </div>

            <div className="flex justify-end gap-3 pt-2">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2.5 rounded-xl bg-white/10 hover:bg-white/15 text-slate-300 text-xs font-bold transition cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="px-6 py-2.5 rounded-xl text-xs font-black shadow-lg transition flex items-center gap-2 cursor-pointer text-[#1E1B4B]"
                style={{ backgroundColor: '#F59E0B' }}
              >
                {formSuccess ? (
                  <>
                    <CheckCircle2 className="w-4 h-4 text-[#1E1B4B]" />
                    <span>Profile Created ✓</span>
                  </>
                ) : (
                  <>
                    <UserPlus className="w-4 h-4 text-[#1E1B4B]" />
                    <span>Complete Onboarding &amp; Save</span>
                  </>
                )}
              </button>
            </div>
          </form>
        )}

        {/* TAB 3: LIST OF ACTIVE & INACTIVE INVITES */}
        {activeTab === 'list' && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <span className="text-xs font-bold text-white block">Invite QR Registry</span>
                <p className="text-[11px] text-slate-400">List of all active, used, and expired nurse invite QRs in <span className="font-mono text-amber-300">/qr_invites</span>.</p>
              </div>
              <button
                type="button"
                onClick={handleGenerateNewInvite}
                className="px-3 py-1.5 rounded-xl bg-[#F59E0B] text-[#1E1B4B] text-xs font-black transition flex items-center gap-1.5 cursor-pointer shadow-sm"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                <span>Generate New</span>
              </button>
            </div>

            <div className="space-y-2 max-h-[50vh] overflow-y-auto pr-1">
              {allInvites.map((inv) => {
                const now = Date.now();
                const isExpired = inv.expiresAt <= now;
                const isActive = !inv.used && !isExpired;

                return (
                  <div
                    key={inv.id}
                    className={`p-3.5 rounded-2xl border flex flex-wrap items-center justify-between gap-3 ${
                      isActive
                        ? 'bg-[#1E1B4B]/40 border-[#F59E0B]/50'
                        : inv.used
                        ? 'bg-emerald-950/20 border-emerald-500/30'
                        : 'bg-white/[0.02] border-white/10 opacity-70'
                    }`}
                  >
                    <div className="space-y-0.5">
                      <div className="flex items-center gap-2">
                        <span className="font-mono font-bold text-xs text-white">{inv.id}</span>
                        {isActive && (
                          <span className="px-2 py-0.5 rounded-full text-[10px] font-black uppercase bg-[#F59E0B] text-[#1E1B4B]">
                            Active
                          </span>
                        )}
                        {inv.used && (
                          <span className="px-2 py-0.5 rounded-full text-[10px] font-black uppercase bg-emerald-500/30 text-emerald-300 border border-emerald-500/40">
                            Used
                          </span>
                        )}
                        {isExpired && !inv.used && (
                          <span className="px-2 py-0.5 rounded-full text-[10px] font-black uppercase bg-red-500/20 text-red-300 border border-red-500/30">
                            Expired
                          </span>
                        )}
                      </div>
                      <p className="text-[10px] text-slate-400">
                        Created: {new Date(inv.createdAt).toLocaleString()} • Expires: {new Date(inv.expiresAt).toLocaleString()}
                      </p>
                    </div>

                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => {
                          setCurrentInvite(inv);
                          setActiveTab('qr');
                        }}
                        className="px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-white text-xs font-semibold transition cursor-pointer"
                      >
                        View QR
                      </button>
                      <button
                        type="button"
                        onClick={() => {
                          navigator.clipboard?.writeText(inv.url);
                        }}
                        className="p-2 rounded-xl bg-white/10 hover:bg-white/20 text-slate-300 hover:text-white transition cursor-pointer"
                        title="Copy link"
                      >
                        <Copy className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
