import React, { useEffect, useState } from 'react';
import QRCode from 'qrcode';
import { Copy, Check, Download } from 'lucide-react';

interface AutoGeneratedQRCodeProps {
  value?: string;
  size?: number;
  qrId?: string;
  countdown?: string;
  pinCode?: string;
  title?: string;
  accentText?: string;
  showActions?: boolean;
  className?: string;
}

/**
 * AutoGeneratedQRCode Component
 * - NO center logo overlay, NO <img> inside QR, NO inner text
 * - High Error Correction ('H') for 100% reliable camera scanning
 * - Uses QRCode.toDataURL with dark: '#1E1B4B', light: '#FFFFFF'
 * - Clean orange border: 4px solid #F59E0B
 * - Displays active link and countdown under QR
 */
export function getPublicBaseUrl(): string {
  return 'https://ais-pre-q5g37b6hiuoaulzo4j4wny-616436889958.us-west2.run.app';
}
export const getBaseUrl = getPublicBaseUrl;

export const AutoGeneratedQRCode: React.FC<AutoGeneratedQRCodeProps> = ({
  value,
  qrId = 'invite-live',
  countdown = '23:59:59',
  pinCode,
  showActions = true,
  className = ''
}) => {
  const [qrDataUrl, setQrDataUrl] = useState<string>('');
  const [copied, setCopied] = useState<boolean>(false);
  const [currentCountdown, setCurrentCountdown] = useState<string>(countdown);

  // Force public URL, never use aistudio.google:
  const refLink = value || `${getPublicBaseUrl()}/nurse-signup?ref=ADMIN_INVITE&id=${qrId}&ts=${Date.now()}`;

  useEffect(() => {
    let isMounted = true;

    async function generateCode() {
      try {
        const url = await QRCode.toDataURL(refLink, {
          width: 300,
          margin: 4,
          errorCorrectionLevel: 'H', // MUST BE H for reliable scan
          color: { dark: '#1E1B4B', light: '#FFFFFF' }
        });
        if (isMounted) {
          setQrDataUrl(url);
        }
      } catch (err) {
        console.error('Failed to generate QR data URL:', err);
      }
    }

    generateCode();

    return () => {
      isMounted = false;
    };
  }, [refLink]);

  // Keep countdown updated
  useEffect(() => {
    setCurrentCountdown(countdown);
  }, [countdown]);

  const handleCopy = () => {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(refLink);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    if (!qrDataUrl) return;
    try {
      const a = document.createElement('a');
      a.href = qrDataUrl;
      a.download = `wecare-qr-${qrId}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    } catch (err) {
      console.warn('Download QR failed', err);
    }
  };

  return (
    <div className={`flex flex-col items-center justify-center text-center ${className}`}>
      {/* Pure clean QR Image with #F59E0B border - NO center logo overlay */}
      {qrDataUrl ? (
        <img
          src={qrDataUrl}
          width="280"
          height="280"
          alt="Auto-generated QR Code"
          style={{
            border: '4px solid #F59E0B',
            borderRadius: '16px',
            display: 'block',
            backgroundColor: '#FFFFFF',
            maxWidth: '100%',
            height: 'auto'
          }}
        />
      ) : (
        <div 
          className="w-[280px] h-[280px] flex items-center justify-center bg-white rounded-2xl animate-pulse"
          style={{ border: '4px solid #F59E0B' }}
        >
          <span className="text-slate-500 font-bold text-xs">Generating Live QR...</span>
        </div>
      )}

      {/* Manual PIN Code if provided */}
      {pinCode && (
        <div className="mt-3 px-5 py-2 rounded-2xl bg-[#1E1B4B] text-white flex items-center gap-2 border-2 border-[#F59E0B] shadow-md">
          <span className="text-xl sm:text-2xl font-mono font-black tracking-widest text-[#F59E0B]">
            PIN: {pinCode}
          </span>
        </div>
      )}

      {/* Debug text under QR for verification */}
      <div className="mt-3 space-y-1 max-w-sm px-2">
        <p style={{ fontSize: '10px' }} className="text-slate-300 font-mono break-all leading-tight">
          {refLink}
        </p>
        <p 
          style={{ color: '#F59E0B' }}
          className="font-mono font-black text-sm"
        >
          Expires in: {currentCountdown}
        </p>
      </div>

      {/* Quick Action Buttons */}
      {showActions && (
        <div className="flex items-center justify-center gap-2 mt-3">
          <button
            type="button"
            onClick={handleCopy}
            className="px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/15 text-white text-xs font-semibold border border-white/10 transition flex items-center gap-1.5 cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-amber-300" />}
            <span>{copied ? 'Copied Link' : 'Copy Link'}</span>
          </button>
          <button
            type="button"
            onClick={handleDownload}
            className="px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/15 text-white text-xs font-semibold border border-white/10 transition flex items-center gap-1.5 cursor-pointer"
          >
            <Download className="w-3.5 h-3.5 text-blue-400" />
            <span>Save Image</span>
          </button>
        </div>
      )}
    </div>
  );
};
