import React, { useState, useEffect, useRef } from 'react';
import QRCode from 'qrcode';
import { AutoGeneratedQRCode } from './AutoGeneratedQRCode';
import { 
  X, 
  QrCode, 
  CheckCircle2, 
  Clock, 
  MapPin, 
  ShieldCheck, 
  Copy, 
  Check, 
  Download, 
  Printer, 
  LogIn, 
  LogOut, 
  Timer, 
  FileCheck, 
  AlertCircle 
} from 'lucide-react';
import { Booking, VisitQRAction } from '../../types';
import { 
  generateBookingCheckin, 
  getBookingCheckin, 
  subscribeToQRUpdates, 
  BookingCheckinRecord 
} from '../../services/qrFirebaseStore';
import { soundFX } from '../../utils/soundEffects';
import { PPESafetyNotice } from './PPESafetyNotice';

interface ClientArrivalQRCodeModalProps {
  booking: Booking | null;
  isOpen: boolean;
  onClose: () => void;
  onSimulateNurseArrival?: (bookingId: string) => void;
  onSimulateNurseCheckout?: (bookingId: string) => void;
  initialTab?: VisitQRAction;
}

export const ClientArrivalQRCodeModal: React.FC<ClientArrivalQRCodeModalProps> = ({
  booking,
  isOpen,
  onClose,
  initialTab
}) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [activeTab, setActiveTab] = useState<VisitQRAction>('check_in');
  const [copiedCode, setCopiedCode] = useState<boolean>(false);
  const [checkinRecord, setCheckinRecord] = useState<BookingCheckinRecord | null>(null);

  // Initialize or fetch the auto-generated unique Job QR:
  // Format: WECARE-{bookingId}-{4-digit-PIN}
  useEffect(() => {
    if (!isOpen || !booking) return;

    const record = generateBookingCheckin(booking.id);
    setCheckinRecord(record);

    if (initialTab) {
      setActiveTab(initialTab);
    } else if (booking.status === 'in_progress' || booking.status === 'ARRIVED_VERIFIED') {
      setActiveTab('check_out');
    } else {
      setActiveTab('check_in');
    }
  }, [isOpen, booking?.id, initialTab]);

  // Subscribe to live checkin updates (e.g. when nurse scans the QR or enters PIN)
  useEffect(() => {
    if (!isOpen || !booking) return;

    const unsubscribe = subscribeToQRUpdates((type, payload) => {
      if (
        (type === 'CHECKIN_VERIFIED' || type === 'CHECKIN_SAVED') &&
        payload && payload.bookingId === booking.id
      ) {
        setCheckinRecord(payload);
        soundFX.playSuccessPing();
      }
    });

    return unsubscribe;
  }, [isOpen, booking?.id]);

  // Render QR Canvas via 'qrcode'
  useEffect(() => {
    if (!isOpen || !booking || !canvasRef.current || !checkinRecord) return;

    // Check-in QR encodes WECARE-{bookingId}-{PIN}
    // Check-out QR encodes WECARE-{bookingId}-OUT
    const qrText = activeTab === 'check_in' 
      ? checkinRecord.qrData 
      : `WECARE-${booking.id}-CHECKOUT-${checkinRecord.pin}`;

    QRCode.toCanvas(
      canvasRef.current,
      qrText,
      {
        width: 250,
        margin: 2,
        color: {
          dark: '#1E1B4B', // Navy
          light: '#FFFFFF'
        },
        errorCorrectionLevel: 'H'
      },
      (err) => {
        if (err) console.error('Error rendering QR canvas', err);
      }
    );
  }, [isOpen, booking, activeTab, checkinRecord]);

  if (!isOpen || !booking || !checkinRecord) return null;

  const isCheckIn = activeTab === 'check_in';
  const pin = checkinRecord.pin;
  const isArrivedVerified = checkinRecord.status === 'ARRIVED_VERIFIED' || booking.pinVerified || booking.status === 'ARRIVED_VERIFIED' || booking.status === 'in_progress';
  const isCheckoutVerified = Boolean(booking.checkoutVerified || booking.status === 'completed');

  const verificationTimeFormatted = checkinRecord.verifiedAt 
    ? new Date(checkinRecord.verifiedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    : (booking.arrivalVerifiedAt ? new Date(booking.arrivalVerifiedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '');

  const handleCopyCode = () => {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(pin);
      setCopiedCode(true);
      soundFX.playSuccessPing();
      setTimeout(() => setCopiedCode(false), 2000);
    }
  };

  const handleDownloadQR = () => {
    if (!canvasRef.current) return;
    try {
      const dataUrl = canvasRef.current.toDataURL('image/png');
      const link = document.createElement('a');
      link.href = dataUrl;
      link.download = `wecare-visit-${booking.id}-${activeTab}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (err) {
      console.warn('Download QR error', err);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/85 backdrop-blur-md overflow-y-auto animate-fadeIn">
      <div 
        className="relative w-full max-w-lg bg-[#0f0a26] border-2 rounded-3xl p-5 sm:p-7 shadow-2xl text-white space-y-4 my-auto max-h-[94vh] overflow-y-auto"
        style={{ borderColor: '#1E1B4B' }}
      >
        {/* Floating Close Button */}
        <button
          type="button"
          onClick={onClose}
          className="absolute top-4 right-4 p-2 rounded-full bg-white/10 hover:bg-white/20 text-slate-300 hover:text-white transition cursor-pointer"
          aria-label="Close"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header */}
        <div className="text-center space-y-1 pt-1">
          <div 
            className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-black uppercase tracking-wider text-[#1E1B4B]"
            style={{ backgroundColor: '#F59E0B' }}
          >
            <QrCode className="w-3.5 h-3.5 text-[#1E1B4B]" />
            <span>Active Doorstep Verification Pass</span>
          </div>
          <h3 className="text-xl sm:text-2xl font-black text-white tracking-tight">
            Doorstep Check-In QR Pass
          </h3>
          <p className="text-xs text-slate-300">
            {booking.serviceName} • Job ID: <span className="font-mono text-amber-300 font-bold">{booking.id}</span>
          </p>
        </div>

        {/* Live Arrival Status Banner */}
        {isArrivedVerified ? (
          <div className="p-3.5 rounded-2xl bg-emerald-500/20 border-2 border-emerald-400/50 flex items-start gap-3 shadow-lg shadow-emerald-950/40">
            <span className="p-2 rounded-xl bg-emerald-500 text-slate-950 shrink-0 font-bold">
              <CheckCircle2 className="w-5 h-5" />
            </span>
            <div className="space-y-0.5 text-left text-xs">
              <span className="text-[10px] font-black uppercase text-emerald-300 tracking-wider">
                LIVE STATUS
              </span>
              <h4 className="font-bold text-white text-sm">
                Nurse Arrived - PIN Verified at {verificationTimeFormatted || '9:32 AM'} ✓
              </h4>
              <p className="text-emerald-100 text-[11px]">
                Caregiver attendance verified on arrival. Job session active.
              </p>
              <p className="text-[10px] text-emerald-200/90 flex items-center gap-1 font-mono pt-0.5">
                <MapPin className="w-3 h-3 text-emerald-400 shrink-0" />
                <span>{checkinRecord.gpsLocation || '14 Trafalgar Road, Kingston 10, Jamaica'}</span>
              </p>
            </div>
          </div>
        ) : (
          <div className="p-3.5 rounded-2xl bg-amber-500/15 border border-amber-400/30 flex items-start gap-3 text-left">
            <span className="p-2 rounded-xl bg-amber-500/20 text-amber-300 border border-amber-400/40 shrink-0">
              <Clock className="w-5 h-5 animate-pulse" />
            </span>
            <div className="space-y-0.5 text-xs">
              <span className="text-[10px] font-black uppercase tracking-wider text-amber-300">
                Ready for Doorstep Check-In
              </span>
              <p className="text-slate-200 leading-relaxed text-[11px]">
                Present this QR code to <strong>{booking.nurseName || 'your assigned nurse'}</strong> at the doorstep or read out the 4-digit PIN below.
              </p>
            </div>
          </div>
        )}

        {/* Dual Mode Switcher Tabs */}
        <div className="flex rounded-2xl bg-black/40 p-1 border border-white/10">
          <button
            type="button"
            onClick={() => setActiveTab('check_in')}
            className={`flex-1 py-2 px-3 rounded-xl text-xs font-black transition flex items-center justify-center gap-2 cursor-pointer ${
              activeTab === 'check_in'
                ? 'bg-[#1E1B4B] text-white border border-[#F59E0B]/50 shadow-md'
                : 'text-slate-300 hover:text-white'
            }`}
          >
            <LogIn className="w-4 h-4 text-emerald-400" />
            <span>1. Doorstep Check-In</span>
            {isArrivedVerified && (
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping" />
            )}
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('check_out')}
            className={`flex-1 py-2 px-3 rounded-xl text-xs font-black transition flex items-center justify-center gap-2 cursor-pointer ${
              activeTab === 'check_out'
                ? 'bg-[#1E1B4B] text-white border border-[#F59E0B]/50 shadow-md'
                : 'text-slate-300 hover:text-white'
            }`}
          >
            <LogOut className="w-4 h-4 text-blue-400" />
            <span>2. Visit Sign-Off</span>
            {isCheckoutVerified && (
              <span className="w-2 h-2 rounded-full bg-emerald-400" />
            )}
          </button>
        </div>

        {/* Pure AutoGeneratedQRCode with #F59E0B border - NO center logo overlay */}
        <div className="flex flex-col items-center justify-center p-4 rounded-3xl bg-white/[0.03] border border-white/10 text-center">
          <AutoGeneratedQRCode
            value={isCheckIn ? checkinRecord.qrData : `WECARE-${booking.id}-CHECKOUT-${pin}`}
            qrId={booking.id}
            pinCode={pin}
            countdown={isArrivedVerified ? "VERIFIED ✓" : "READY FOR SCAN"}
            showActions={false}
          />
        </div>

        {/* Remote Family / WhatsApp Access */}
        <div className="p-3.5 rounded-2xl bg-white/5 border border-white/10 text-left space-y-2">
          <div className="flex items-center justify-between text-xs">
            <span className="font-bold text-white flex items-center gap-1.5">
              <span>👨‍👩‍👧 Remote Family Relay</span>
            </span>
            <span className="text-[10px] text-amber-300 font-mono">
              PIN: {pin}
            </span>
          </div>
          <p className="text-[11px] text-slate-300">
            If elderly client has no phone at the door, relatives abroad or at work can text this PIN to the visiting nurse:
          </p>
          <div className="flex flex-wrap items-center gap-2 pt-0.5">
            <a
              href={`https://wa.me/?text=${encodeURIComponent(
                `Hello! Here is the We Care doorstep arrival PIN for ${booking.clientName}: ${pin} (Job #${booking.id}). Please enter this PIN to start the visit.`
              )}`}
              target="_blank"
              rel="noreferrer"
              className="px-3 py-1.5 rounded-xl bg-[#25D366]/20 hover:bg-[#25D366]/30 text-emerald-300 border border-[#25D366]/40 text-xs font-bold transition flex items-center gap-1"
            >
              <span>📲 Send via WhatsApp</span>
            </a>
            <button
              type="button"
              onClick={handleDownloadQR}
              className="px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/15 text-slate-200 text-xs font-semibold transition flex items-center gap-1 cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Save QR Image</span>
            </button>
          </div>
        </div>

        {/* Address & Geofence Assurance */}
        <div className="p-3 rounded-2xl bg-white/5 border border-white/10 text-xs text-slate-300 flex items-center justify-between">
          <div className="flex items-center gap-1.5">
            <MapPin className="w-3.5 h-3.5 text-red-400" />
            <span className="truncate max-w-[220px]">{booking.clientAddress}, {booking.zone}</span>
          </div>
          <span className="text-emerald-400 font-bold text-[10px]">14 Trafalgar Rd GPS ✓</span>
        </div>
      </div>
    </div>
  );
};
